name: fotografia
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  camera: ^0.10.0+1
  path_provider: ^2.0.11
  permission_handler: ^9.0.0
  image_picker: ^0.8.4+4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
